CREATE TABLE menus (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    menu_id INT UNSIGNED NULL COMMENT 'ID',
    name VARCHAR(255) NOT NULL COMMENT '名称',
    name_kana VARCHAR(255) NULL COMMENT '名称（かな）',
    category VARCHAR(255) NULL COMMENT 'カテゴリ',
    description TEXT NULL COMMENT '説明文',
    price INT NULL COMMENT '金額',

    page_url VARCHAR(255) NULL COMMENT '詳細ページURL',
    thumbnail_url VARCHAR(255) NULL COMMENT 'サムネイルURL',
    
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='メニューマスタ';
